[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

# -O3 for release
[profile.release]
opt-level = 3

[workspace]
members = [
    "zvm",
    "zetac"
]

[dependencies]
bumpalo = "3.17.0"
#once_cell = "1.21.3"
#zetac = { path = "./zetac" }
