[package]
name = "zeta-lang"
version = "0.1.0"
edition = "2024"

# -O3 for release
[profile.release]
opt-level = 3
lto = true
target-cpu = "native"

[workspace]
members = [
    "zetac", "zeta", "ir"
]

[dependencies]
bumpalo = "3.17.0"
criterion = "0.6.0"
#once_cell = "1.21.3"
#zetac = { path = "./zetac" }
