[package]
name = "zeta-lang"
version = "0.1.0"
edition = "2024"

# -O3 for release
[profile.release]
opt-level = 3
lto = true
target-cpu = "native"

[workspace]
members = [
    "zetac", "zeta", "commons"
]

[dependencies]
bumpalo = "3.19.0"
ir = { path = "commons" }
criterion = "0.6.0"
rand = "0.9.1"
