[package]
name = "scribe-parser"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
pest = "2.8.1"
pest_derive = "2.8.1"
thiserror = "2.0.12"
seahash = "4.1.0"
ir = { path = "../ir" }
zetaruntime = { path = "../zetaruntime" }