
[package]
name = "zetac"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3

[dependencies]
cranelift = "0.120"
cranelift-module = "0.120"
cranelift-jit = "0.120"
cranelift-object = "0.120.0"
cranelift-native = "0.120.0"
pest = "2.8.0"
pest_derive = "2.8.0"
lazy_static = "1.5.0"
anyhow = "1.0.98"