[package]
name = "zetaruntime"
version = "0.1.0"
edition = "2024"

[dependencies]
#once_cell = "1.21.3"
#zetac = { path = "./zetac" }
dashmap = "7.0.0-rc2"
seahash = "4.1.0"
lazy_static = "1.5.0"
libc = "0.2"
crossbeam-deque = "0.8"
crossbeam-queue = "0.3"
once_cell = "1.21.3"
